### ISSUE TITLE
--set-wallpaper shifts desktop icons to left side

### ISSUE THREAD

**Issue by darkoverlordofdata** [helloSystem/Filer#100]
when I use launch Filer --set-wallpaper, the desktop icons move from the right side to the left side, and move up so that the 1st icon is covered by the global menu. 

I can fix this using Preferences -> Desktop and click on 'Apply' - the icons move back to the right.
![issue2](https://user-images.githubusercontent.com/1262194/122802343-4257ae00-d293-11eb-9afa-84940d127bb6.png)

**Comment by probonopd** [comment]
I can reproduce this.
