### ISSUE TITLE
When you paste or drag the file to the trash can, the error message "Operation not supported" appears.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Filer#112]
**Describe the bug**
Drag the file to the trash can, or right-click to paste it, an error message "Operation not supported" will appear.

**To Reproduce**
1. Select the file or folder and Right-Click
2. Select "Cut or Copy"
3. Go to ' Trash bin'
4. Right-Clicking "Paste "
5. See error message "Operation not supported"

Or
1. Open ' Trash bin'
2. Select the file or folder.
3. Move to 'Trash bin'
4. See error message "Operation not supported"

**Expected behavior**
The file or folder will appear on the trash bin.

**Screenshots**
![20210712_110252](https://user-images.githubusercontent.com/44593430/125225160-5bd39f00-e301-11eb-85d9-1b9894184cdf.jpg)

**Version (please complete the following information):**
 - Live ISO and installed
 - FreeBSD version  12.2
 - helloSystem build https://github.com/helloSystem/ISO/releases/tag/experimental-12.2 `0F28`
 - Running in a virtual machine: no

**Computer (please complete the following information):**
 - Device: Acer Aspire 3810T

**Additional context**
no.

**Comment by probonopd** [comment]
In bug reports, please always mention the __exact__ version of the ISO you are using.

**Comment by probonopd** [comment]
Trash handling has been overhauled. Please comment here if the issue persists after build 0H224.
