### ISSUE TITLE
Highlight selected icons using a grey rounded rectangle

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Filer#114]
**Is your feature request related to a problem? Please describe.**
Selecting the icon of a file in the Mac system can also clearly display the picture or icon, but just superimposing blue on it not only can’t see its icon clearly, but it’s also uncertain about the scope of the icon.

**Describe the solution you'd like**
When you select a file, a semi-transparent square with a black background and white border will be added to the background of the icon.
It’s not that the icon turns blue.

**Describe alternatives you've considered**
When selecting a file in Mac OS 10.4.11, a semi-transparent square with a black background and a white border will be added to the background of the icon.

**Additional context**
_In Desktop_
![image](https://user-images.githubusercontent.com/44593430/126085400-b1baa252-493f-481d-9f38-d1d76cd43608.png)
_In Folder_
![image](https://user-images.githubusercontent.com/44593430/126085765-448081a8-70c6-48a6-ac8c-84d3bffbaaa3.png)
![image](https://user-images.githubusercontent.com/44593430/126085542-a064c8ed-ba68-4827-bfbd-41a67d217af8.png)

**Comment by probonopd** [comment]
This is what we have now:

![image](https://user-images.githubusercontent.com/2480569/126439402-b0a8d729-1f02-41e4-8dd4-1589de74327f.png)

There are still some issues though.

When the second line of text is longer than the first and is elided (contains `...`), then the box highlighting the text gets too large and the text is not centered correctly.

![image](https://user-images.githubusercontent.com/2480569/126439614-6c28fe86-d049-4300-be80-5d702069848f.png)

Does anyone know how to fix this? Probably something along the lines of
https://doc.qt.io/qt-5/qtwidgets-widgets-elidedlabel-example.html

around

https://github.com/helloSystem/Filer/blob/8315764740bcdb6e6ef48e598d0f171df651ea20/src/folderitemdelegate.cpp#L166-L175

Any help appreciated.

**Comment by louies0623** [comment]
I think it is caused by the font again.

**Comment by probonopd** [comment]
Why do you think this?

**Comment by louies0623** [comment]
Nothing. :l

**Comment by louies0623** [comment]
> 你為什麼這麼認為？



> Why do you think this?
This should not be caused by the font, but the blue rectangle still corresponds to the full folder name without omitting the'...' which is the hidden text.

**Comment by probonopd** [comment]
The feature is implemented. Rendering issues are discussed elsewhere, hence closing here.
