### ISSUE TITLE
Support drag and drop to open documents with applications

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#12]
![image](https://user-images.githubusercontent.com/2480569/203411482-208e59b6-66fc-4804-af44-8a5c77a119dd.png)

Support drag and drop to open documents with applications.

**Comment by probonopd** [comment]
If a document icon is dragged over an application (`.AppDir`/`.app` bundle) icon, then the file manager should determine whether the application is capable of handling that type of file, and if yes, launch the application and open the file. If no, then refuse to accept the drag operation unless the user forces it by holding down the Alt key. (Similar to the Mac.)

**Comment by probonopd** [comment]
Please do not start working on this without prior discussion on how Filer should decide which file types an application can handle.

**Comment by linuxkettle** [comment]
Ah, like the great Windows feature. "Drag me onto py.exe.py"

**Comment by probonopd** [comment]
Yes! We should also discuss this topic with @mszoek

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/203411451-4e54fcf8-6721-4cf0-ba4a-1134ffb10ff3.png)

**Comment by probonopd** [comment]
Implemented.
Currently without checking whether the receiving application can handle the dropped MIME type.
