### ISSUE TITLE
Bring Filer to the front when needed

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#122]
Now that we have `org.freedesktop.FileManager1.ShowItems` it would be nice if Filer would come to the front then this is called, so that the user can actually see it.

The following does not work.

How to achieve this?

```
FreeBSD% git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 37904e8..57e71eb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -35,6 +35,7 @@ pkg_check_modules(SYSTEM_LIBS REQUIRED
     gio-2.0
     gio-unix-2.0
     xcb
+    x11
 )
 
 pkg_check_modules(LIBFM REQUIRED libfm>=1.2.0)
diff --git a/src/desktopwindow.cpp b/src/desktopwindow.cpp
index d6c238d..fea9394 100644
--- a/src/desktopwindow.cpp
+++ b/src/desktopwindow.cpp
@@ -270,6 +270,12 @@ void DesktopWindow::onOpenDirRequested(FmPath* path, int target) {
       }
     }
     newWin->show();
+
+    // Bring Filer to front; FIXME: This does not work yet
+    newWin->activateWindow();
+    newWin->raise();
+    Display *dpy;
+    XRaiseWindow(dpy, newWin->winId());
 }
 
 void DesktopWindow::resizeEvent(QResizeEvent* event) {
```

cc @mszoek

**Comment by mszoek** [comment]
Is `dpy` opened anywhere before calling `XRaiseWindow()`? If not, you should do `dpy = XOpenDisplay(":0");` first and then `XCloseDisplay(dpy);` after. I think it might also work better with `newWin->effectiveWinId()` but I have not had good luck with making windows raise or lower reliably :(

**Comment by probonopd** [comment]
It works! It works!

**Comment by probonopd** [comment]
https://user-images.githubusercontent.com/2480569/133944490-a0e28017-79b0-4fd0-9e9d-7661f905cde7.mp4

**Comment by linuxkettle** [comment]
Why does Filer do this?
```
probono: LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
```

**Comment by probonopd** [comment]
This is debug output, is is everything Filer puts out on a command line. Will be removed in the next build.
