### ISSUE TITLE
Need to optimize search

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Filer#147]
I want to search in the upper left corner to search for only specific file names, such as .png or .mp3, like the two images below.
However, since the file manager does not have the search function on the Tab menu, the search function in the upper left corner is very limited, which increases the difficulty of searching.

- Mac OS
 <img width="814" alt="Hj255" src="https://user-images.githubusercontent.com/44593430/160441697-2a228bc6-2e78-4b01-91b6-7113e16c15ab.png">

- Easyfind 
![easyfind](https://user-images.githubusercontent.com/44593430/160441730-c26bc5f9-f413-4ff9-b81c-987e602f9a00.jpeg)

**Comment by probonopd** [comment]
Currently we have some "Find" functionality in the Extras menu. Press Command-F to open the Find window.

**Comment by louies0623** [comment]
It is indeed necessary, because in the current file manager mode, it is very inconvenient, and a series of windows will make people faint, and they do not know where they are now.

**Comment by probonopd** [comment]
Then they are not Mac users from the good old days ;-)

**Comment by louies0623** [comment]
But you can keep this mode and leave it as an option on the tabmenu.

**Comment by probonopd** [comment]
Yes, we don't want to remove it but the Non Spatial mode (also known as Explorer mode) is currently broken and needs to be fixed.

**Comment by louies0623** [comment]
I recently saw a video about the Apple conference that feels relevant, you can watch it.[Mac Osx Tiger Keynote Intro Part 1
](https://youtu.be/9m9gxxHRvFM?t=136)

**Comment by probonopd** [comment]
Well, for that stuff we have https://github.com/helloSystem/hello/issues/33. Hence closing here, let's continue there.
