### ISSUE TITLE
Desktop (Filer) crashes when right-clicking on a folder in the Trash(Filer) workspace.

### ISSUE THREAD

**Issue by Anvith00** [helloSystem/Filer#155]
## Steps to reproduce:

1. Open Trash(Filer).
2. Right-click on a deleted file/ folder in the Trash workspace.

![image](https://user-images.githubusercontent.com/24383877/201292849-7fb15e9d-f0bc-4ea7-b5b8-8efec01a51f7.png)

> ** (process:1840): WARNING **: 02:49:25.457: The directory '~/Templates' doesn't exist, ignoring it
> 
> (process:1840): GVFS-WARNING **: 02:49:25.461: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> ** (process:1840): WARNING **: 02:49:25.467: terminal launch isn't known, consider report it to LibFM developers
> Failed qApp->installTranslator(qtTranslator)
> 
> ** (process:1840): WARNING **: 02:49:25.470: terminal launch isn't known, consider report it to LibFM developers
> 
> ** (process:1840): WARNING **: 02:49:25.471: modules directory is not accessible
> 
> (process:1840): GVFS-WARNING **: 02:49:25.471: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.472: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.473: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> QMetaObject::connectSlotsByName: No matching signal for on_actionOpenAndCloseCurrentWindow_triggered()
> QMetaObject::connectSlotsByName: No matching signal for on_actionFolderProperties_triggered()
> QMetaObject::connectSlotsByName: No matching signal for on_actionDeleteWithoutTrash_triggered()
> invoking IsSupported() failed for remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor:: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gtk.vfs.UDisks2VolumeMonitor was not provided by any .service files (g-dbus-error-quark, 2)
> 
> (process:1840): GVFS-WARNING **: 02:49:25.657: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.659: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.659: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.664: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.666: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.667: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.668: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.670: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.670: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.677: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
> (process:1840): GVFS-WARNING **: 02:49:25.693: The peer-to-peer connection failed: Error when getting information for file “/var/run/user/1001/gvfsd”: No such file or directory. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
> 
>

**Comment by Anvith00** [comment]
https://user-images.githubusercontent.com/24383877/201293542-e11c5c8a-3b5d-4c38-a3e0-60c38c160d46.mp4

**Comment by probonopd** [comment]
This is no longer the case since we have thrown out the evil `trash://`.
