### ISSUE TITLE
Dragging a document onto the white area of an opened folder window crashes

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Filer#164]
When using Spring-loaded folders function, it will be terminated by the right-click menu.

[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/205506486-89a669f6-94ac-4458-b18f-1b6033be8934.webm)

**Comment by probonopd** [comment]
Right now, you need to drag the icon into the window that is opened.
I know that this is not ideal, but I haven't found a better solution yet.

**Comment by louies0623** [comment]
Isn't it just that when you drag the file, you release the mouse and the options appear.

**Comment by louies0623** [comment]
Then the window will automatically release the mouse when it comes out, you should have noticed.

**Comment by louies0623** [comment]
When the window comes out, the mouse will be released automatically, and I have no time to move the file to the window.

**Comment by probonopd** [comment]
> When the window comes out, the mouse will be released automatically, and I have no time to move the file to the window.

I cannot reproduce this.

**Comment by louies0623** [comment]
I reproduced a whole chain of crashes.
[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/206812075-a4092c1e-4478-464c-8d7c-f11864de8306.webm)

**Comment by louies0623** [comment]
> I cannot reproduce this.
It's going to crash in the end, right?

**Comment by probonopd** [comment]
No, it works for me on my development machine. Will have to try on the Live ISO.

**Comment by probonopd** [comment]
I can reproduce the issue on hello-0.8.0_0H242-FreeBSD-13.1-amd64.

**Comment by probonopd** [comment]
This seems to have to do with it:

```
QCoreApplication::postEvent: Unexpected null receiver
QMetaObject::connectSlotsByName: No matching signal for on_actionOpenAndCloseCurrentWindow_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionFolderProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionDeleteWithoutTrash_triggered()
QIODevice::read (QProcess): device not open
```

**Comment by louies0623** [comment]
It moves the location of the folder on the desktop, and then pulls the file in and it crashes.
