### ISSUE TITLE
Support drag-and-drop of URLs from web browsers onto the Desktop

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#21]
The nemo file manager seems to support this. So should we.

https://askubuntu.com/a/1008821

> My solution: use the nemo file manager (sudo apt install nemo) instead of Ubuntu's default of nautilus. Now, in nemo you can just drag and drop links right out of the Chrome/Chromium browser search bar and into the nemo file manager. Done!

**Comment by linuxkettle** [comment]
I'm just touching up on my C++, it's been a while since I've used it, but if i
you change the dragEnterEvent code to check if the URI uses HTTP or FTP, you can use a Qt function to download the file.

I know how to do it in QML...

**Comment by probonopd** [comment]
Maybe @moochris can help?

**Comment by moochris** [comment]
I'll have a look 🙂

**Comment by probonopd** [comment]
It looks like `dnddest.cpp` has the beginnings of this for the `text/uri-list` MIME type?

References:
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types#link

**Comment by probonopd** [comment]
Upstream does also not support this yet.

**Comment by probonopd** [comment]
It's been implemented.
