### ISSUE TITLE
Get rid of computer:///

### ISSUE THREAD

**Issue by LouiIPSW** [helloSystem/Filer#34]
When I Right Click On The File System I see all 0
![Capture](https://user-images.githubusercontent.com/79132875/108174836-0956d380-7111-11eb-88c3-04a0948b96de.PNG)

This Have been Installed On vbox And The real size is 16 GB

and thx!

**Comment by probonopd** [comment]
WIth https://github.com/helloSystem/Filer/pull/59 the contents of `computer://` are now shown on the desktop. Hence the importance of `computer://` has decreased and we can think about removing it from the sidebar.
