### ISSUE TITLE
Put 'Eject' into context menu for disks/mountpoints

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#41]
Especially in [Spatial mode](https://github.com/helloSystem/hello/issues/79) there is currently no way to eject/unmount disks/loop-mounted partitions.

Whenever the user right-clicks on a directory, we should check whether something is mounted at that directory (a mountpoint) and if yes, offer "Eject" rather than "Move to Trash" in the context menu.

**Comment by probonopd** [comment]
* __File > Eject__: Whenever one or more folders is/are selected, we may want to check whether something is mounted at that location(s), and add a "Eject" menu item, with an action similar to `libfm-qt/placesview.cpp`: `op->unmount(mount);`

* __Context menu > Eject__ in place of "Move to Trash": Whenever the right-click context menu is opened on one or more folders, we may might want to check whether something is mounted at that location(s), and change the context menu accordingly, showing "Eject" rather than "Move to Trash", with an action similar to `libfm-qt/placesview.cpp`: `op->unmount(mount);`

What shall happen if a combination of files, folders and mountpoints is selected? (What happens on a Mac in this case)?

**Comment by probonopd** [comment]
> What shall happen if a combination of files, folders and mountpoints is selected? (What happens on a Mac in this case)?

Ejecting

* If one removable device is selected, the context menu and the File menu have an item `Eject "<Name of volume>"`
* If two or more removable devices are selected, the context menu has an item `Eject`; for consistency I think the File menu should also have an item `Eject` (on the Mac, the File menu has nothing)
* If one or more removable devices plus at least one other object are selected, then neither the context menu nor the File menu have any notion of Eject

**Comment by probonopd** [comment]
Someone needs to analyze and backport https://github.com/lxqt/libfm-qt/pull/660/files.

**Comment by moochris** [comment]
Sure, I'll look at this next when I get some time. 

If we had devices on the desktop then drag to trash/eject would be nicer 🙂

**Comment by probonopd** [comment]
Indeed.

> If we had devices on the desktop

This just takes hanging a few lines (not much effort) as explained in https://github.com/helloSystem/Filer/issues/9:

![](https://user-images.githubusercontent.com/2480569/92182209-67397c80-ee4b-11ea-933a-9ec4a8af05c4.png)

But what we need is to have _both_ devices _and_ files/folders...

**Comment by probonopd** [comment]
Turns out we can solve this by a simple text file:

https://github.com/helloSystem/ISO/commit/8f4b2f0333945afc544db5abb42774fec4a488ec#diff-febf34f96aa46897233532c13ceeaef78597b401b13affefd08399013e8934d0
