### ISSUE TITLE
Alternating row colors for Details view 

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#42]
Use alternating row colors for Details view like QTableView/QTableWidget `setAlternatingRowColors(true)`.

![image](https://user-images.githubusercontent.com/2480569/109694628-51530d00-7b8b-11eb-9a44-f420e7669e6c.png)

The alternate color itself is defined in the stylesheet that we are loading:

https://github.com/helloSystem/QtPlugin/blob/4705ee86c4f3563042bd52ee78fe11c98515878d/stylesheet.qss#L62

**Comment by linuxkettle** [comment]
Haven't you already done this?

**Comment by probonopd** [comment]
Indeed!
