### ISSUE TITLE
Show name of the volume instead of something like da0s1

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#58]
```
% gpart show -l '/dev/da0s1'       
gpart: No such geom: /dev/da0s1.

% gpart show -l /dev/da0  
=>     32  1014752  da0  MBR  (496M)
       32       31       - free -  (16K)
       63  1014678    1  (null)  (495M)
  1014741       43       - free -  (22K)
```

Looks like this disk has no name (`(null)`), even though it has the name "FAT" which the Mac shows correctly...

**Comment by probonopd** [comment]
We are after the __Volume label__ specifically.

https://en.wikipedia.org/wiki/Volume_(computing)#Volume_label

**Comment by grahamperrin** [comment]
How, precisely, was the disk formatted? Using what tool(s)?

**Comment by probonopd** [comment]
I don't remember. Possibly on a Mac with Disk Utility.

**Comment by grahamperrin** [comment]
1. `gpart show da0`
2. `lsblk da0`
3. `sudo gdisk /dev/da0`

**Comment by probonopd** [comment]
```
% sudo hexdump -C /dev/da0 | grep FAT                 
00007e20  96 7b 0f 00 80 01 29 fb  07 d5 1d 46 41 54 20 20  |.{....)....FAT  |
```

**Comment by probonopd** [comment]
```
% gpart show da0
=>     32  1014752  da0  MBR  (496M)
       32       31       - free -  (16K)
       63  1014678    1  fat32  (495M)
  1014741       43       - free -  (22K)

% lsblk da0
DEVICE         MAJ:MIN SIZE TYPE                              LABEL MOUNT
da0              0:160 496M MBR                                   - -
  <FREE>         -:-    16K -                                     - -
  da0s1          0:161 495M fat32                                 - /media/da0s1
  <FREE>         -:-    22K -                                     - -

% sudo gdisk /dev/da0
sudo: gdisk: command not found
```

**Comment by probonopd** [comment]
This does the trick but needs sudo:

```
% sudo fstyp -l /dev/da0s1
msdosfs FAT
```

**Comment by probonopd** [comment]
On the Mac, these "Volume labels" are used as the directory names for the mountpoints as well, unlike what we currently have:

![image](https://user-images.githubusercontent.com/2480569/112729053-8a806200-8f2a-11eb-82bc-9ae3030f25b9.png)

**Comment by grahamperrin** [comment]
### glabel(8)

https://man.freebsd.org/glabel(8)

`glabel list` 

… and so on. 

Hint: you'll not get the label whilst the file system is mounted.

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/112748685-b4369900-8fbd-11eb-91f2-57b4c475c6b5.png)

**Comment by DamjanJovanovic** [comment]
bsdisks already uses `fstyp` to find the filesystem type, so it knows which mount command to use, but there's no `-l`. It uses the GEOM label, but maybe should use something else, for the "IdLabel" property in:
```
sudo dbus-send --system --print-reply \
--dest=org.freedesktop.UDisks2 \
/org/freedesktop/UDisks2/block_devices/da1 \
org.freedesktop.DBus.Properties.GetAll \
string:org.freedesktop.UDisks2.Block
```

I'll do some further tests and let you know.

**Comment by DamjanJovanovic** [comment]
GEOM does expose the volume label, parse the XML output of `sysctl kern.geom.confxml` and look under the "LABEL" class. A "MYUSB" label on /dev/da1 has the form:
```
<class id="0xffffffff81afcda0">
    <name>LABEL</name>
    <geom id="0xfffff800c9aa9800">
        <name>da1</name>
        <provider id="0xfffff800ca320a00">
          <name>msdosfs/MYUSB</name>
          ...
        </provider>
        ...
    </geom>
    ...
</class>
```
Note that apart from trimming the filesystem prefix and slash, the label from GEOM has to be URL-decoded (unless your XML library already did that for you).

However that disappears when the filesystem is mounted.

bsdisks also exposes it over D-Bus, obtained from GEOM before mounting (for the filesystems it manages, anyway):
```
sudo dbus-send --system --print-reply \
--dest=org.freedesktop.UDisks2 \
/org/freedesktop/UDisks2/block_devices/da1 \
org.freedesktop.DBus.Properties.Get \
string:org.freedesktop.UDisks2.Block \
string:IdLabel
```

If you need the label of a mounted filesystem even when unmanaged by bsdisks, I think `fstyp -l` is the only way.

ZFS volumes don't have labels, and their dataset names (eg. zroot/var/log) seem to come from the first string in the output of `zfs get -H canmount` instead.

**Comment by grahamperrin** [comment]
A PCManFM-Qt view of a non-mounted ZFS file system in my _copperbowl_ pool: 

![PCManFM-Qt](https://user-images.githubusercontent.com/192271/112778454-7f1d5b80-903c-11eb-8e60-32964dde2ab1.png)

* an unusual example, in that the icon for the device must not be clicked. 

Ambiguity can be problematic:

![image](https://user-images.githubusercontent.com/192271/112778993-ac1e3e00-903d-11eb-898f-45c0bd9ed595.png)

* each of the six `/` bookmarks was for a separate location
* none refers to `/`

**Comment by probonopd** [comment]
@DamjanJovanovic unfortunately this does not work for me:

```
% sysctl kern.geom.confxml | grep '<label'    
            <label></label>
            <label>zfs0</label>
            <label>gptboot0</label>
            <label>efiboot0</label>

% sudo dbus-send --system --print-reply \
--dest=org.freedesktop.UDisks2 \
/org/freedesktop/UDisks2/block_devices/da0s1 \
org.freedesktop.DBus.Properties.GetAll \
string:org.freedesktop.UDisks2.Block
method return time=1617007998.984579 sender=:1.14 -> destination=:1.16 serial=23 reply_serial=2
   array [
      dict entry(
         string "Configuration"
         variant             array [
            ]
      )
      dict entry(
         string "CryptoBackingDevice"
         variant             object path "/"
      )
      dict entry(
         string "Device"
         variant             array of bytes "/dev/da0s1"
      )
      dict entry(
         string "DeviceNumber"
         variant             uint64 0
      )
      dict entry(
         string "Drive"
         variant             object path "/org/freedesktop/UDisks2/drives/da0"
      )
      dict entry(
         string "HintAuto"
         variant             boolean false
      )
      dict entry(
         string "HintIconName"
         variant             string ""
      )
      dict entry(
         string "HintIgnore"
         variant             boolean false
      )
      dict entry(
         string "HintName"
         variant             string ""
      )
      dict entry(
         string "HintPartitionable"
         variant             boolean false
      )
      dict entry(
         string "HintSymbolicIconName"
         variant             string ""
      )
      dict entry(
         string "HintSystem"
         variant             boolean false
      )
      dict entry(
         string "Id"
         variant             string "0000000000000000000"
      )
      dict entry(
         string "IdLabel"
         variant             string ""
      )
      dict entry(
         string "IdType"
         variant             string "vfat"
      )
      dict entry(
         string "IdUUID"
         variant             string ""
      )
      dict entry(
         string "IdUsage"
         variant             string "filesystem"
      )
      dict entry(
         string "IdVersion"
         variant             string ""
      )
      dict entry(
         string "MDRaid"
         variant             object path "/"
      )
      dict entry(
         string "MDRaidMember"
         variant             object path "/"
      )
      dict entry(
         string "PreferredDevice"
         variant             array of bytes "/dev/da0s1"
      )
      dict entry(
         string "ReadOnly"
         variant             boolean false
      )
      dict entry(
         string "Size"
         variant             uint64 519515136
      )
      dict entry(
         string "Symlinks"
         variant             array [
            ]
      )
   ]
```

**Comment by probonopd** [comment]
According to @crees

> fstyp -l /dev/disk gets you the label
but you will have to be in group operator
or just put in devfs rules to give 644 rather than just 640 on drive nodes are you're all good

**Comment by vermaden** [comment]
I am using device nodes as mount point as its consistent and I that way each devices behaves the same.

Remember that:
- many removable devices does not have labels for filesystems
- you can also use device model as mount point but with many partitions you must 'artificially' enumerate these partitions
- you also need to make sure that all those labels and model names are sanitized ... `tr -c -d` comes handy here

I have better proposal ... leave the 'technical' mount points as they are now - they are sure to work properly - and change these names in the graphical/presentation layer. For example you can display different names (labels or model) on the desktop then the actual mountpoint. You can also leave current device naming and add caption (text displayed after on-mounse-over a device) with its label and/or model.

**Comment by probonopd** [comment]
Needed to run `sudo devfs ruleset 10`, now I get 

```
% fstyp -l /dev/da0s1
msdosfs FAT
```

**Comment by probonopd** [comment]
Need in `/etc/rc.conf`:

```
devfs_load_rulesets="YES"
devfs_system_ruleset="system"
```

**Comment by probonopd** [comment]
In perparation for this, I committed
* https://github.com/helloSystem/ISO/commit/9b852f29e295d1d258fcd6fb6318e77b0c10e9ca
* https://github.com/helloSystem/ISO/commit/e1f4e643e6ff3ee63cd2eaec81f722fbe8f0f82d

Possibly we also need to edit
* https://github.com/helloSystem/ISO/blob/experimental/overlays/uzip/furybsd-live-settings/files/usr/local/bin/furybsd-init-helper (remains to be seen)

**Comment by probonopd** [comment]
We are getting somewhere.

![image](https://user-images.githubusercontent.com/2480569/112905113-2c9a7880-90ea-11eb-9419-940ef28e64fc.png)
