### ISSUE TITLE
Bookmark reordering fails

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/Filer#63]
From <https://github.com/helloSystem/Filer/issues/9#issuecomment-808908297>: 

![attempting to move a bookmark](https://user-images.githubusercontent.com/192271/112756630-0091d100-8fde-11eb-88df-2fc36ea880d4.png)

1. drag
2. drop

Expected: 

3. drop in the required place

Actual result: 

3. bounce back to the wrong place.

**Comment by probonopd** [comment]
Reordering bookmarks works for me on helloSystem build: 0E57 for commit: 80061bf.
`computer:///` is not a concept we want to have.

**Comment by grahamperrin** [comment]
Today I can't reproduce the issue, but it feels very fiddly. 

When I encountered the issue, it's wasn't just fiddly. I tried repeatedly (for a couple of minutes) to drop in a suitable place, it didn't work.

**Comment by probonopd** [comment]
Please comment in case you can reproduce it on the unedited Live ISO or unchanged installed system.

**Comment by grahamperrin** [comment]
> "alien", like if it is coming from Gnome. 

I don't use GNOME.

**Comment by grahamperrin** [comment]
There's certainly a bug, probably upstream. 

Part of the problem is the plus icon appearing where it should not appear. Bad UX.
