### ISSUE TITLE
Do not show mounted disks in ~/Desktop

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#67]
Now the volumes show up not only on the Desktop (where they should) but also when one goes to `~/Desktop` in Filer. They should not be shown in the latter location.

![image](https://user-images.githubusercontent.com/2480569/112913984-35e01100-90fb-11eb-8a81-81bc2774f0b0.png)

cc @moochris

**Comment by moochris** [comment]
This should be easy to fix - use a FolderModel directly in desktopwindow.cpp instead of a CachedFolderModel.

The latter is cached by the path when first created for the desktop window and gets reused when you browse to the desktop folder.

**Comment by probonopd** [comment]
Getting `error: no member named 'modelFromPath' in 'Fm::FolderModel'` then.

**Comment by moochris** [comment]
I mean it's simple but you need to change it a little more - you want `model_` to be a `FolderModel` now.

You don't need `modelFromPath()` for `FolderModel` - you can just initialise it in the constructor and then (where you currently call `modelFromPath()`:
```
FmFolder* folder = fm_folder_from_path(fm_path_get_desktop());
model_.setFolder(folder);
model_->addComputerFiles();
```

same further down in `DesktopWindow::setDesktopFolder()`

**Comment by moochris** [comment]
In fact I think `folder_` is already the folder you need for the above

**Comment by probonopd** [comment]
Getting a segfault now. Suspect it may have to do with what is going on in ``DesktopWindow::~DesktopWindow()`? I never know what I have to do in  `~` (this is the nice thing about Python - you don't have to deal with such things).

Would you be able to send a PR?

**Comment by moochris** [comment]
Yes, no problem - leave it with me.

Yes, I agree, writing Python is always a relief after writing C++ for so long and dealing with all that stuff :smile:

**Comment by probonopd** [comment]
Now we have an "interesting" side effect @moochris:
When you go to `~/Desktop` and press F5 there to refresh, then the volumes disappear from the desktop.

I hope this is fixable...

**Comment by moochris** [comment]
Doh! I'll take a look

**Comment by probonopd** [comment]
Thanks @moochris for having resolved this issue. :+1:
