### ISSUE TITLE
Minimized windows do not get un-minimized when folder is double clicked

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#79]
* Open a folder
* Minimize the window (right-click on the title bar, minimize; or select "Hide all" from the System menu)
* Open the same folder by double-clicking its icon

Expected behavior:
The existing folder window is un-minimized

Actual behavior:
Nothing. The user thinks it is impossible to open the folder

@moochris could you have a look please?

**Comment by moochris** [comment]
We raise and activate the window, but I'm not sure if we can un-minimize it... I'll have a look, but it might not be possible from Qt

**Comment by moochris** [comment]
Oh, nevermind - found it:

https://doc.qt.io/qt-5/qwidget.html#showNormal

**Comment by probonopd** [comment]
Tested it, works :+1: hence closing. Thanks!
