### ISSUE TITLE
Get rid of extra line at the left of Spatial windows

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#82]
![image](https://user-images.githubusercontent.com/2480569/115994704-6327be00-a5d8-11eb-9517-f944fe5465d0.png)

Maybe we need to increase the ListView that holds the icons a few pixels to the left in Spatial mode?

cc @moochris

**Comment by moochris** [comment]
In spatial mode, we hide the sidebar and a couple of other things - maybe it's a remnant of that?

**Comment by probonopd** [comment]
Confirming that #83 solves it. Thanks @moochris
