### ISSUE TITLE
Show a message if the folder is empty

### ISSUE THREAD

**Issue by linuxkettle** [helloSystem/Filer#87]
When I first tried hello on the Live CD, I thought Filer was broken because when I opened my home folder, there was just nothing there.

If you open a empty folder, you get an empty Filer window, like this:
![image](https://user-images.githubusercontent.com/64388266/116763080-1430bd00-aa0c-11eb-936c-2946f36a9784.png)

I think it would be a good idea to have something like this:
![image](https://user-images.githubusercontent.com/64388266/116763161-6b369200-aa0c-11eb-8637-f993611ac2fc.png)
Just to let people know why they can't see anything.

Does this sort of thing show in PCManFM-Qt?

**Comment by probonopd** [comment]
Why should an empty folder show anything but, well, an empty folder?
