### ISSUE TITLE
Display volumes on the desktop

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#9]
We want to show disks on the desktop.

![image](https://user-images.githubusercontent.com/2480569/92182209-67397c80-ee4b-11ea-933a-9ec4a8af05c4.png)

In `desktopwindow.cpp` change `Fm::CachedFolderModel::modelFromPath(fm_path_get_desktop());` to `
Fm::CachedFolderModel::modelFromPath(fm_path_new_for_uri("computer://"));` in two places.

Then, instead of the files in the desktop folder determined by `XDG_DESKTOP_DIR`, the volumes are shown on the desktop.

Now, how can we show __both__? Best would be if we could put more than one model into the `Fm::CachedFolderModel`... is it possible?

Reference:
https://github.com/lxqt/pcmanfm-qt/issues/1192#issuecomment-686775394

**Comment by grahamperrin** [comment]
For what it's worth I'd make this an option, not a default.

**Comment by probonopd** [comment]
Why? The Mac has been doing this since before System 1.0 was released. Even the Lisa did this. To me this is essential of how a desktop needs to work.

**Comment by grahamperrin** [comment]
I always chose to not show them on the desktop. Preferred to see them in the sidebar of Finder.

**Comment by probonopd** [comment]
> Now, how can we show both?

Maybe @moochris knows how to combine two models into one?

**Comment by moochris** [comment]
I do not 🙂

I guess we probably want to solve this through inheritance in the models themselves?

We don't want to mess with the model returned by the `computer://` URI (because that's used in browser mode too), but define a new one like `desktop://` that inherits from the folder model but adds in the stuff in `computer://` abstracted away so it can be reused like this.

How hard can it be? They did this stuff back in the 80s 😀

**Comment by probonopd** [comment]
Yes, that sounds like a plan.

**Comment by probonopd** [comment]
@moochris do you think [QConcatenateTablesProxyModel](https://doc.qt.io/qt-5/qconcatenatetablesproxymodel.html) could be helpful here?

>QConcatenateTablesProxyModel takes multiple source models and concatenates their rows.
>
>In other words, the proxy will have all rows of the first source model, followed by all rows of the second source model, and so on.

**Comment by moochris** [comment]
@probonopd - hmm, possibly - will have a look (probably next weekend now - got some unpacking to do)

**Comment by moochris** [comment]
Right, I managed to grab a spare half an hour: https://github.com/helloSystem/Filer/pull/59

Seems to be working OK from testing. I guess you can remove the link to 'Computer' now?

**Comment by moochris** [comment]
OK, that was easy enough to solve - I just had to keep the FmFolder for 'computer://' around until the destructor.

New devices now appear when inserted.

**Comment by probonopd** [comment]
You can do wonders in _half an hour_. This is simply awesome!
Thank you so much. Huge improvement.
https://github.com/helloSystem/Filer/pull/59

**Comment by grahamperrin** [comment]
https://github.com/helloSystem/Filer/issues/9#issuecomment-808860749

>> remove the link to 'Computer' now?

That was the first thing that I wanted to restore, my first attempt failed, the second attempted succeeded and neither bookmark is in the required place: 

![attempting to move a bookmark](https://user-images.githubusercontent.com/192271/112756630-0091d100-8fde-11eb-88df-2fc36ea880d4.png)

https://github.com/helloSystem/Filer/issues/9#issuecomment-757349284

> … an option, not a default.

I see no option: 

![no option](https://user-images.githubusercontent.com/192271/112756707-5fefe100-8fde-11eb-898f-0c90f86da2a7.png)

**Comment by probonopd** [comment]
I don't like options because they make things difficult. Options result in systems being different from each other, which makes support more cumbersome than needed.

**Comment by grahamperrin** [comment]
> I don't like options …

That's quite a departure from: 

>> … [The user in full control.](https://github.com/helloSystem/hello#what)

Disallowing a fundamental desktop preference is quite unlike what I'd expect with any Mac. 

If user preferences such as these are to be excluded by design, it might help to flesh out your vision under https://hellosystem.github.io/docs/developer/ux-guidelines.html

Thanks

**Comment by probonopd** [comment]
> The user in full control.

What is meant by this: The user has full access to the filesystem, and cannot be locked out of the system.

What is not meant by this: Having 1,001 configuration options - users who are looking for this might be better served by KDE Plasma?

**Comment by grahamperrin** [comment]
> 1,001 configuration options

If you edit https://hellosystem.github.io/docs/developer/ux-guidelines.html please find a different number.
