### ISSUE TITLE
Add "Move to Trash" menu item

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#96]
Add "Move to Trash" menu item. Shortcut: Ctrl-Backspace (gets mapped to Alt-Backspace on helloSystem by default).

**Comment by probonopd** [comment]
The __Edit__ menu currently has an item that always says "Delete", even if Filer is set up to put things into the Trash rather than directly delete them.

The context menu that appears when you right-click a file or folder does this correctly.

Here is the code in question:

https://github.com/helloSystem/Filer/blob/bce6e515fdbe6a14482825a5dd1a2f6d3cd64834/libfm-qt/filemenu.cpp#L362-L370

But this does not get reflected in the __Edit__ menu item. It should.

**Comment by probonopd** [comment]
Shortcut is now implemented, but it still always says "Delete" rather than "Move to Trash". Bug?

**Comment by linuxkettle** [comment]
Says 'Move to Trash' for me...

**Comment by probonopd** [comment]
In the context menu (only) or also in the main menu?
