### ISSUE TITLE
Add "Open" and "Open with..." to File menu

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Filer#98]
Add "Open" (Command-ArrowDown and Command-O) and "Open with..." (Command-Shift-O) to File menu.

Also consider the case that more than one file/directory is selected.
All of this is already implemented for the context menu that appears on right-click, but we also want it in the main menu.

**Comment by probonopd** [comment]
`CreateNewMenu` is called from both `./libfm-qt/filemenu.cpp` (for the main menu) and by `./libfm-qt/foldermenu.cpp` (for the context menu). 

So probably something similar should be done for "Open", "Open with...", and similar menu entries that we want to have in both places.

**Comment by moochris** [comment]
There is a common function for create new - it's `createFileOrFolder()` as defined in `libfm-qt/utilities.h`.

The functions are in those three places because they are different classes entirely with a different way to get the current path (e.g. compare `MainWindow::on_actionNewBlankFile_triggered()` with `DesktopWindow::onNewBlankFile()` because that is where the common function is called from.

I think unfortunately the only way to have just _one_ implementation from the menu would be a complete rewrite/refactor so that the desktop window isn't a completely different 'thing' than the main windows.

**Comment by probonopd** [comment]
> I think unfortunately the only way to have just one implementation from the menu would be a complete rewrite/refactor so that the desktop window isn't a completely different 'thing' than the main windows.

Yes, that makes sense to me. Unfortunately it's a bit out of reach for me given the level of my C++ knowledge at this point.

**Comment by probonopd** [comment]
For now I just mirrored what is done for the other functions; it works but I still think it's more code duplication than would be ideal.

**Comment by probonopd** [comment]
Implemented for "Open". As for "Open with...", we will probably need an entirely different implementation that can be per-file and is not based on desktop files anyway.

**Comment by linuxkettle** [comment]
How does open with decide what apps open what?

I can't see it in the helloSystem developer docs anywhere...

**Comment by probonopd** [comment]
This is because we have not implemented this part yet. Pending alignment with @mszoek.
We want to be able to set this information for all files of the same mime type, and still be able to override it on a per-file basis (the latter probably being stored in extended attributes in the file system).

**Comment by mszoek** [comment]
> This is because we have not implemented this part yet. Pending alignment with @mszoek.

Yes. Sorry, I got sidetracked with repackaging and release engineering stuff. Still on my list and maybe this is a good opportunity to talk about some ideas for `open` and LaunchServices.

> (Currently it is using whatever the dreaded XDG spec uses, as implemented by libfm. But we want to do away with that because it is cumbersome and unflexible.)

I'm not sure we can completely avoid XDG here. As much as I don't like it, other applications (e.g. Firefox, Chrome) open files and will use the XDG mappings. I plan to patch or replace commands like `xdg-open` and `xdg-mime` to be wrappers around LaunchServices, but not every application uses those. Many will be linked against `libxdg` or other toolkits for manipulating those XDG files directly. A patched `xdg-utils` might cover most cases though.

As far as implementing stuff in Filer, I'll be implementing [these APIs](https://developer.apple.com/documentation/coreservices/launch_services?language=objc) in LaunchServices.framework. `LSOpenCFURLRef` is probably the most relevant here. CoreFoundation is plain C so nice and easy to hook into!

**Comment by probonopd** [comment]
> CoreFoundation is plain C so nice and easy to hook into!

:+1:

**Comment by linuxkettle** [comment]
How would we associate files with apps? Have a registry? Can apps add new mime types to the database?

**Comment by probonopd** [comment]
That'd be the LaunchServices-like database @mszoek was referring to.
